import { FloorPlanAnalysis } from '../types/floorPlan';

export const MOCK_FLOOR_PLAN_ANALYSIS: FloorPlanAnalysis = {
  summary:
    'Boceto interpretado como edificación compacta de una planta con sala-comedor central, cocina lateral, dos dormitorios y un baño compartido.',
  mappingSteps: [
    {
      step: 1,
      title: 'Validar contorno exterior',
      description: 'Confirma el perímetro total del plano antes de medir cuartos internos.',
      specification: 'Dimensiones exteriores sugeridas: 10.0 m (ancho) × 8.5 m (largo).',
    },
    {
      step: 2,
      title: 'Ubicar zona social',
      description: 'Identifica la sala o sala-comedor como eje de circulación principal.',
      specification: 'Sala-comedor: 4.2 m × 3.8 m, techo 2.50 m, ventana en muro norte.',
    },
    {
      step: 3,
      title: 'Mapear cocina y servicios',
      description: 'Relaciona cocina con acceso directo desde la zona social.',
      specification: 'Cocina: 2.8 m × 2.4 m, puerta corrediza hacia sala, ventana este.',
    },
    {
      step: 4,
      title: 'Registrar dormitorios',
      description: 'Asigna medidas a cada recámara respetando muros compartidos.',
      specification:
        'Dormitorio principal: 3.6 m × 3.2 m. Dormitorio secundario: 3.0 m × 2.8 m.',
    },
    {
      step: 5,
      title: 'Confirmar baño y circulación',
      description: 'Verifica puertas, pasillos y ventilación del baño.',
      specification: 'Baño: 2.2 m × 1.8 m, ventilación alta, puerta desde pasillo central.',
    },
    {
      step: 6,
      title: 'Revisar aberturas',
      description: 'Marca ventanas y puertas según orientación del boceto.',
      specification: 'Mínimo 10% de ventanas respecto al área de cada habitación habitable.',
    },
  ],
  rooms: [
    {
      id: 'sala',
      name: 'Sala-comedor',
      type: 'living',
      x: 0,
      y: 0,
      width: 4.2,
      length: 3.8,
      height: 2.5,
      hasWindows: true,
      hasDoor: true,
    },
    {
      id: 'cocina',
      name: 'Cocina',
      type: 'kitchen',
      x: 4.2,
      y: 0,
      width: 2.8,
      length: 2.4,
      height: 2.5,
      hasWindows: true,
      hasDoor: true,
    },
    {
      id: 'dorm-principal',
      name: 'Dormitorio principal',
      type: 'bedroom',
      x: 0,
      y: 3.8,
      width: 3.6,
      length: 3.2,
      height: 2.5,
      hasWindows: true,
      hasDoor: true,
    },
    {
      id: 'dorm-secundario',
      name: 'Dormitorio secundario',
      type: 'bedroom',
      x: 3.6,
      y: 3.8,
      width: 3.0,
      length: 2.8,
      height: 2.5,
      hasWindows: true,
      hasDoor: true,
    },
    {
      id: 'bano',
      name: 'Baño',
      type: 'bathroom',
      x: 4.2,
      y: 2.4,
      width: 2.2,
      length: 1.8,
      height: 2.5,
      hasWindows: false,
      hasDoor: true,
    },
  ],
  ceilingHeight: 2.5,
  totalWidth: 7.0,
  totalLength: 7.0,
  notes: [
    'Las medidas son aproximadas según el boceto; validar en sitio con cinta métrica.',
    'El modelo 3D representa proporciones, no una construcción ejecutiva.',
  ],
};
